export interface LineageAncestor {
  generation: number;
  nameAr: string;
  nameEn: string;
  titleAr?: string;
  titleEn?: string;
  descAr?: string;
  descEn?: string;
  isPivotal?: boolean;
  isProphet?: boolean;
  isRoot?: boolean;
}

/**
 * نسب النبي محمد ﷺ الشريف المتفق عليه في السيرة النبوية المطهرة:
 * محمد بن عبد الله بن عبد المطلب بن هاشم بن عبد مناف بن قصي بن كلاب بن مرة
 * بن كعب بن لؤي بن غالب بن فهر (قريش) بن مالك بن النضر بن كنانة بن خزيمة
 * بن مدركة بن إلياس بن مضر بن نزار بن معد بن عدنان.
 */
export const PROPHETIC_LINEAGE: LineageAncestor[] = [
  {
    generation: 1,
    nameAr: 'محمد ﷺ',
    nameEn: 'Muhammad ﷺ',
    titleAr: 'سيد ولد آدم وخاتم النبيين والمرسلين',
    titleEn: 'Master of Humanity & Seal of the Prophets',
    descAr: 'المصطفى المجتبى، المبعوث رحمة للعالمين، أطهر الناس نسباً وخلقاً وأعظمهم قدوة.',
    descEn: 'The Chosen Messenger, sent as a mercy to all creation, of the purest lineage and noblest character.',
    isProphet: true,
  },
  {
    generation: 2,
    nameAr: 'عبد الله',
    nameEn: 'Abdullah',
    titleAr: 'والد النبي ﷺ وأصغر بني عبد المطلب',
    titleEn: 'Beloved father of Prophet Muhammad ﷺ',
    descAr: 'والد النبي ﷺ، لُقّب بالذبيح الثاني افتداءً له بمئة من الإبل، وتوفي بالمدينة وهو في ريعان شبابه.',
    descEn: 'Father of the Prophet ﷺ, known for his noble demeanor, passed away in Yathrib (Madinah).',
    isPivotal: true,
  },
  {
    generation: 3,
    nameAr: 'عبد المطلب',
    nameEn: 'Abd al-Muttalib',
    titleAr: 'شيبة الحمد، سيد قريش وحافر زمزم',
    titleEn: 'Chieftain of Quraysh & Rediscoverer of Zamzam',
    descAr: 'حفر بئر زمزم بعد اندثارها، وكان كافلاً للنبي ﷺ في طفولته المبكرة ورعاه بحنو عظيم.',
    descEn: 'Rediscovered the sacred well of Zamzam, stood firm before Abraha, and lovingly fostered young Muhammad ﷺ.',
    isPivotal: true,
  },
  {
    generation: 4,
    nameAr: 'هاشم',
    nameEn: 'Hashim',
    titleAr: 'عمرو العُلا، صاحب الإيلاف ورحلتي الشتاء والصيف',
    titleEn: 'Initiator of Quraysh trade covenants',
    descAr: 'أول من سنّ رحلتي الشتاء والصيف المذكورتين في سورة قريش، وسُمي هاشماً لهشمه الخبز وإطعامه الحجاج.',
    descEn: 'Pioneered the historic Summer and Winter trade journeys and generously fed the pilgrims in Makkah.',
    isPivotal: true,
  },
  {
    generation: 5,
    nameAr: 'عبد مناف',
    nameEn: 'Abd Manaf',
    titleAr: 'المغيرة، جامع السيادة والشرف',
    titleEn: 'Distinguished elder and leader of Makkah',
    descAr: 'كان يُسمى قمر البطحاء لجماله ووسامته، وإليه تنتمي الفروع القرشية الكبرى.',
    descEn: 'Renowned for his charisma, wisdom, and leadership across the sacred precincts of Makkah.',
  },
  {
    generation: 6,
    nameAr: 'قصي',
    nameEn: 'Qusayy',
    titleAr: 'مُجمّع قريش، باني دار الندوة وصاحب السقاية والرفادة',
    titleEn: 'Unifier of Quraysh & Founder of Dar an-Nadwa',
    descAr: 'وحّد بطون قريش في مكة بعد تفرقهم، وأسس دار الندوة للشورى، ونال سقاية الحجيج ورفادتهم ولواء الحرب.',
    descEn: 'Unified the scattered clans of Quraysh, established the Council Hall (Dar an-Nadwa), and organized pilgrim welfare.',
    isPivotal: true,
  },
  {
    generation: 7,
    nameAr: 'كلاب',
    nameEn: 'Kilab',
    titleAr: 'حكيم قريش وصاحب الشرف الموروث',
    titleEn: 'Noble forefather uniting major lineages',
    descAr: 'سُمي كلاباً لاقتنائه كلاب الصيد، وإليه يلتقي نسب النبي ﷺ مع نسب أمّه آمنة بنت وهب.',
    descEn: 'The common ancestor where the lineages of the Prophet ﷺ and his mother Aminah bint Wahb converge.',
  },
  {
    generation: 8,
    nameAr: 'مرة',
    nameEn: 'Murrah',
    titleAr: 'جد العشائر القرشية',
    titleEn: 'Respected patriarch of noble clans',
    descAr: 'إليه يلتقي نسب النبي ﷺ مع نسب الصديق أبي بكر رضي الله عنه، وكذلك طلحة بن عبيد الله.',
    descEn: 'Ancestral convergence point with Abu Bakr as-Siddiq and Talha ibn Ubaydillah (may Allah be pleased with them).',
  },
  {
    generation: 9,
    nameAr: 'كعب',
    nameEn: 'Ka\'b',
    titleAr: 'خطيب العرب ومبشرهم بالبعثة الخاتمة',
    titleEn: 'Eloquence & early monotheistic proclaimer',
    descAr: 'كان يجمع قومه يوم الجمعة (يوم العروبة) ويخطب فيهم مذكراً بالتوحيد ومبشراً بالنبي المبعوث.',
    descEn: 'Gathered his people weekly, preaching monotheism and foretelling the arrival of the final Prophet.',
  },
  {
    generation: 10,
    nameAr: 'لؤي',
    nameEn: 'Lu\'ayy',
    titleAr: 'سيد الحرم وقائد قومه',
    titleEn: 'Chieftain of the sacred valley',
    descAr: 'إليه يلتقي نسب النبي ﷺ مع الفاروق عمر بن الخطاب رضي الله عنه.',
    descEn: 'Ancestral convergence point with Umar ibn al-Khattab (may Allah be pleased with him).',
  },
  {
    generation: 11,
    nameAr: 'غالب',
    nameEn: 'Ghalib',
    titleAr: 'صاحب المنعة والقوة',
    titleEn: 'Protector and noble elder',
    descAr: 'كان فارساً مقداماً وحامياً لجوار البيت العتيق.',
    descEn: 'Known for his valiance, defending the pilgrims and honoring sacred agreements.',
  },
  {
    generation: 12,
    nameAr: 'فهر (قريش)',
    nameEn: 'Fihr (Quraysh)',
    titleAr: 'قريش، جماع القبيلة ومبتدأ التسمية',
    titleEn: 'Eponymous ancestor of the Quraysh tribe',
    descAr: 'هو «قريش» عند جمهرة النسابين، ومن لم يلده فهر فليس بقرشي، وله مكانة سامية في جزيرة العرب.',
    descEn: 'The patriarch recognized as the definitive origin of the Quraysh tribe; all authentic Qurayshis descend from him.',
    isPivotal: true,
  },
  {
    generation: 13,
    nameAr: 'مالك',
    nameEn: 'Malik',
    titleAr: 'سيد قومه في مكة وجوارها',
    titleEn: 'Esteemed leader of the Makkan confederacy',
    descAr: 'اشتهر بالحكمة والعدل وفصل الخصومات بين القبائل.',
    descEn: 'Celebrated for arbitrating disputes with integrity and wisdom.',
  },
  {
    generation: 14,
    nameAr: 'النضر',
    nameEn: 'Al-Nadr',
    titleAr: 'قيس مكة، صاحب الوجه النضير',
    titleEn: 'The radiant leader of the lineage',
    descAr: 'سُمي النضر لنضارة وجهه وجمال سمته وكرم طباعه.',
    descEn: 'Named for his radiant countenance, grace, and generosity.',
  },
  {
    generation: 15,
    nameAr: 'كنانة',
    nameEn: 'Kinana',
    titleAr: 'سيد مضر المصطفى من ولد إسماعيل',
    titleEn: 'The Chosen of the children of Isma\'il',
    descAr: 'قال النبي ﷺ: «إن الله اصطفى كنانة من ولد إسماعيل»، وهو رأس قبائل كنانة الكبرى.',
    descEn: 'The Prophet ﷺ stated: "Indeed Allah chose Kinana from the children of Isma\'il."',
    isPivotal: true,
  },
  {
    generation: 16,
    nameAr: 'خزيمة',
    nameEn: 'Khuzaymah',
    titleAr: 'المنظم الشجاع لحلفاء البيت',
    titleEn: 'Guardian of the tribal compacts',
    descAr: 'كان حازماً عادلاً، صان جوار الكعبة المشرفة وحمى الحجاج من قطاع الطرق.',
    descEn: 'Protected the sacred pilgrimage routes and preserved harmony in the Hijaz.',
  },
  {
    generation: 17,
    nameAr: 'مدركة',
    nameEn: 'Mudrikah',
    titleAr: 'عامر، مدرك شرف آبائه',
    titleEn: 'Upholder of ancestral virtue',
    descAr: 'لُقّب مدركة لأنه أدرك كل ما كان في آبائه من الفضل والمجد والمنعة.',
    descEn: 'Earned his title by embodying all the noble virtues and distinction of his predecessors.',
  },
  {
    generation: 18,
    nameAr: 'إلياس',
    nameEn: 'Ilyas',
    titleAr: 'أول من أهدى البدن إلى الحرم',
    titleEn: 'Pioneer of pilgrim offerings to the Ka\'bah',
    descAr: 'كان معظماً للحرم، وهو أول من أهدى البدن إلى البيت الحرام وسنّ ذلك في العرب.',
    descEn: 'Deeply revered the Sanctuary, pioneering the tradition of offering sacrificial camels to the Ka\'bah.',
  },
  {
    generation: 19,
    nameAr: 'مضر',
    nameEn: 'Mudar',
    titleAr: 'مضر الحمراء، رأس القبائل المضرية',
    titleEn: 'Patriarch of the widespread Mudarite tribes',
    descAr: 'سيد أهل زمانه، وكان أحسن صوتاً وغناءً للإبل، وإليه تنتمي جمهرة العرب العدنانية.',
    descEn: 'Renowned for his melodious voice and supreme standing among the tribes of Arabia.',
  },
  {
    generation: 20,
    nameAr: 'نزار',
    nameEn: 'Nizar',
    titleAr: 'أبو القبائل ومورث السيادة',
    titleEn: 'Father of northern Arabian dynasties',
    descAr: 'سُمي نزاراً لنزارته وقلة نظيره في الحسن والشرف، وإليه تتفرع مضر وربيعة وإياد وأنمار.',
    descEn: 'A pillar of ancestral dignity whose descendants formed the greatest Arabian confederacies.',
  },
  {
    generation: 21,
    nameAr: 'معد',
    nameEn: 'Ma\'add',
    titleAr: 'فارس العرب وقاهر الغزاة',
    titleEn: 'Heroic defender against foreign campaigns',
    descAr: 'كان صاحب فتوح ومنعة، حارب الغزاة في زمن بختنصر، وحافظ على ذرية إسماعيل عليه السلام.',
    descEn: 'Defended the Arabian Peninsula with courage, preserving the monotheistic heritage of Isma\'il.',
  },
  {
    generation: 22,
    nameAr: 'عدنان',
    nameEn: 'Adnan',
    titleAr: 'رأس العرب العدنانية وسليل خليل الله إبراهيم',
    titleEn: 'The Patriarch of the Adnanite Arabs',
    descAr: 'سليل نبي الله إسماعيل بن إبراهيم الخليل عليهما السلام، وإليه ينتهي النسب النبوي المتفق عليه إجماعاً.',
    descEn: 'Direct descendant of Prophet Isma\'il, son of Ibrahim (peace be upon them), and consensus terminus of prophetic genealogy.',
    isRoot: true,
    isPivotal: true,
  },
];
